### ISSUE TITLE
Thank you so much for your contribution

### ISSUE THREAD

**Issue by NoPhaseNoKill** [blundell/monorepo#1]
Often in OSS, we seldom celebrate success. This is just a shoutout and huge thank you for your contribution to the community, specifically regarding your monorepo example and blog post found here: https://blog.blundellapps.co.uk/make-a-monorepo-for-your-android-projects/.

Not only is it clear and concise, but it delves into the nitty gritty and doesn't skimp on extremely subtle nuances that have HUGE impacts in a monorepo using gradle's build system.

I have been reading documentation, and attempting to implement this structure on a personal project in my spare time for well over a month now - and it's been laughable how we've gotten a build system so complicated - with such useless and terrible documentation. Get rid of all the cruft, all the noise, all the sample templates and just replace it with this. 

If you haven't noticed my frustration with the previous documentation, words cannot fathom what your blog post and example project have just done for me. It's felt like such a simple task, burdened by over-complexity, to which you've opened the door.

Considering the recent multi-profile/hierarchical structure/composite builds (specifically 8.3+) - do you plan on making an update or future blog post for this? Please feel free to tag me or email me if you do any further blog posts - you've won a lifetime member.

THIS is what the gradle docs should have been. THIS is the gold standard. THIS is what the gradle docs should STILL be. This is just out of this world fantastic.

**Comment by blundell** [comment]
thank you so much for the kind words :-) that's lovely to here! I'm glad to have helped you 🙌 

Ooh I haven't looked into the changes in 8.3 myself yet, but when I do if I find something that requires a new approach or change, I'll write a follow up blog for sure :-) thank you for pointing this out to me! 

Wish you the best of luck with your own projects 💯

**Comment by NoPhaseNoKill** [comment]
@blundell You're more than welcome good sir. Please find inside a little christmas gift :).

I'm actually in the midst of setting one up now, so when I'm finished with the basic structure I'd be more than happy to lodge a PR if you'd like me to? Potentially we could branch it signifying different versions?
